# Navbar title
site_name: ozfortress Docs
# Both site_name and site_url are needed for the configuration file
site_url: https://docs.ozfortress.com
# Author
site_author: ozfortress
# Site description
site_description: >-
  ozfortress houses all of its documentation for league play, services, guides, FAQs and more within this docs site. 
# Repository
repo_name: ozfortress/ozfortress_docs
# Repisitory URL to link
repo_url: https://github.com/ozfortress/ozfortress_docs
copyright: >
  Copyright &copy; 2022 - 2023 ozfortress
nav:
    - Home: index.md
    - Rulesets:
      - Global ruleset: rules/global.md
      - Sixes ruleset: rules/sixes.md
      - Highlander ruleset: rules/highlander.md
      - Community Guidelines: rules/community_guidelines.md
      - User Policy: rules/user_policy.md
      - Infractions: rules/infractions.md
      - Transfers: rules/transfers.md
    - League Info:
      - General: info/general.md
      - Anti-Cheat & You: info/anticheat_and_you.md
      - Bans:
        - Ban Types: info/ban_types.md
        - Anti-Cheat Bans: info/anticheat_bans.md
        - VAC Bans: info/vac_bans.md
        - Infraction Threshold Bans: info/infraction_bans.md
        - Other Bans: info/other_bans.md
        - Past Bans: info/past_bans.md
      - Staff: info/staff.md
      - Map History:
        - Sixes: info/map_history/#sixes-6v6-map-history
        - Highlander: info/map_history/#highlander-hl-map-history
        - Tournaments/Cups: info/map_history/#tournamentscups
      - Server Configs: info/server_configs.md
    - Guides:
      - Your guide to the guides: guides/landing.md
      - Newbie Guide: guides/newbie_guide.md
      - Book a Server: guides/book_a_server.md
      - Self-managed Servers: guides/selfmanaged_servers.md
    - FAQ: 
      #- General: faq/landing.md
      #- Misconduct: faq/misconduct.md
      #- Anti-Cheat: faq/anticheat.md
      - Demo Requests: faq/demo_requests.md
    - Support & Reporting: support/landing.md
    - Back to ozfortress.com: 'https://ozfortress.com'
theme:
  name: 'material'
  custom_dir: overrides
  favicon: 'img/logo.svg'
  logo: 'img/logo.svg'
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  palette:
    # Palette toggle for Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: fontawesome/solid/moon
        name: Switch to Dark Mode
    # Palette toggle for Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to Light Mode
  features:
   - search.highlight
   - search.suggest
   - search.share
   - navigation.instant
   - navigation.tracking
   - navigation.tabs
   - navigation.expand
   - navigation.top
   - toc.follow
   - content.tooltips
markdown_extensions:
  - admonition
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.betterem
  - toc:
      permalink: true
plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: false
      fallback_to_build_date: true # remove this prior to launch
extra:
  generator: false
  use_directory_urls: false
  social:
    - icon: fontawesome/solid/globe
      link: https://ozfortress.com
    - icon: fontawesome/brands/discord
      link: https://discord.gg/7E6kC2H
    - icon: fontawesome/brands/patreon
      link: https://www.patreon.com/ozfortress/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ozfortress
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCKnMgeTAHzdttd8TXE9UOgw
    - icon: fontawesome/brands/steam
      link: https://steamcommunity.com/groups/ozfortress
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/ozfortress
    - icon: fontawesome/brands/github
      link: https://github.com/ozfortress
#  consent:
#    title: Hey, we use cookies!
#    description: >- 
#      We use cookies to recognize your repeated visits and preferences, as well
#      as to measure the effectiveness of our documentation and whether players can
#      find what they're searching for. With your consent, you're helping us to
#      make our documentation better.
#  actions:
#    - accept
#    - manage
extra_css:
  - stylesheets/extra.css